### ISSUE TITLE
Enforce release version in package.json

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/JAprilFools#137]
Investigate automated actions to do this.

**Comment by yuri-norwood** [comment]
Current candidate: [justincy/github-action-npm-release](https://github.com/marketplace/actions/automatic-github-release)

> Automatically generate a release when the package.json version changes. The release name and tag will match the new version.

**Comment by yuri-norwood** [comment]
Example workflow:

```yml
name: Auto

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: justincy/github-action-npm-release@v1.2.0
```
