### ISSUE TITLE
Add .eslintrc

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/JAprilFools#58]
* Lines should be no longer than 80 characters, except for lines that:
  * Are comments ending with a long URL.
  * Contain a regex literal. (constructor requires string escaping)
* Statement blocks e.g. `if` blocks, must have braces, one following the statement clause, and one on its own line.
* Any `;` used as a statement terminator must be at the end of the line. Note: this includes comments, see comment style rules.

Additionally set up an action to enforce this.
```yml
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
```
